### ISSUE TITLE
Cannot select theme, only color schema

### ISSUE THREAD

**Issue by szakerx** [tinted-theming/base16-jetbrains#11]
Hi, after importing base-16-material-darker.jar my color schema has changed, but Intellij has no theme at all. Should it be like  this? 
![image](https://user-images.githubusercontent.com/48438688/122638380-089c7100-d0f4-11eb-8b51-e932ce2a38e8.png)

**Comment by JamyGolden** [comment]
@adilosa do you have an idea why this is happening? I've run into this myself. I can change the colorscheme by going `Settings -> Editor -> Color Scheme`, but I can't change the theme as mentioned above. This ends up with the code area using base16, but the rest of the app uses the Theme.

![image](https://user-images.githubusercontent.com/602472/177890398-6abcc0f4-f6b8-41f0-92eb-47039d37f713.png)

**Comment by adilosa** [comment]
There was repo that supposedly fixed this. It looks like they added an `ide-theme.mustache` in addition to the editor theme. Seems like that should do it.

https://github.com/ShiromMakkad/base16-jetbrains-ide/blob/master/templates/ide-theme.mustache

**Comment by JamyGolden** [comment]
Ah nice, I'll test that out and create a PR.

**Comment by JamyGolden** [comment]
Hey @adilosa :smile: I've been speaking to the maintainer of the repo you linked to (https://github.com/ShiromMakkad/base16-jetbrains-ide) about moving development to this repo and adding them as a maintainer of this repo. I've created a branch (still working on it) where I've cherry-picked most of the commits from their repo: https://github.com/tinted-theming/base16-jetbrains/tree/new-main

Bringing that across to this repo would solve this github issue by styling the whole IDE. I know you've mentioned before that you're not going to be very active in this repo, but I wanted to check in with you to make sure you're ok with that.

**Comment by adilosa** [comment]
Hey @JamyGolden, looks good to me! Thanks for getting that together. Appreciate the consideration :)

**Comment by JamyGolden** [comment]
I'm closing the issue now since things have been merged and this repo has styling for the syntax as well as the UI :smile:
