### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by binury** [tinted-theming/base16-jetbrains#2]
Color schemes should be set so that language-specific options automatically inherit from general defaults. Here is an example of a configuration which has been modified to automatically inherit Python settings from the parent color scheme (Pycharm) [base16-ocean.dark.icls.txt](https://github.com/adilosa/base16-idea/files/298657/base16-ocean.dark.icls.txt)

**Comment by JesusMtnez** [comment]
:+1: to this issue. Not all themes are avaliable in this repository and some of them may be outdated. 

@adilosa there is some script/tool you use to generate this themes for IntelliJ? I'll be glad to help updating / adding themes.

**Comment by adilosa** [comment]
@JesusMtnez I'm pretty sure I used the chriskempson/base16-builder tool, probably using the IDEA files found here: https://github.com/chriskempson/base16-builder/tree/master/templates/idea

It looks like that tool is deprecated now, and the themes should be rebuilt with one of the new builder tools listed in the README.

**Comment by adilosa** [comment]
@JesusMtnez I updated all the color schemes. The underlying `templates/default.mustache` probably need some work. It's based on the same templates as before - [chriskempson's old templates](https://github.com/chriskempson/base16-builder/blob/master/templates/idea/) - which are now four years old.

**Comment by JesusMtnez** [comment]
@adilosa Thank you!

**Comment by binury** [comment]
Looks great 🙂
