### ISSUE TITLE
Material Themes

### ISSUE THREAD

**Issue by mallowigi** [tinted-theming/base16-jetbrains#7]
First of all thanks for implementing my plugin :) 

Second, using templates to generate settings is a great idea, but perhaps you could take a look at this: 
http://www.material-theme.com/docs/development/external-themes/

This explains how to bundle a theme plugin to the Jetbrains repository using the Material Theme as an underlaying base.

**Comment by re1** [comment]
First of all thank you for this wonderful theme :+1:. It seems like externals were added just a few weeks after I finished my template (had to wait a little for my PR). As time is scarce it might take while but this is definitely worth implementing.
